// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qjviwkanngckcctsytmk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFqdml3a2Fubmdja2NjdHN5dG1rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4MDU4NjgsImV4cCI6MjA3MTM4MTg2OH0.5e9v539vg1ZLqil4EYVbhkLoOjQQP1JkyOAYTMK45oo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});